### ISSUE TITLE
Docker build fails 

### ISSUE THREAD

**Issue by bainss** [devxp-tech/backstage#5]
Hi When trying to build a docker image I get the following error

`
#14 583.8 packages/backend/src/plugins/kubernetes.ts:9:60 - error TS2345: Argument of type '{ logger: winston.Logger; config: Config; }' is not assignable to parameter of type 'KubernetesEnvironment'.
#14 583.8   Property 'catalogApi' is missing in type '{ logger: winston.Logger; config: Config; }' but required in type 'KubernetesEnvironment'.
#14 583.8
#14 583.8  9   const { router } = await KubernetesBuilder.createBuilder({
#14 583.8                                                               ~
#14 583.8 10     logger: env.logger,
#14 583.8    ~~~~~~~~~~~~~~~~~~~~~~~
#14 583.8 11     config: env.config,
#14 583.8    ~~~~~~~~~~~~~~~~~~~~~~~
#14 583.8 12   }).build();
#14 583.8    ~~~
#14 583.8
#14 583.8   node_modules/@backstage/plugin-kubernetes-backend/dist/index.d.ts:250:5
#14 583.8     250     catalogApi: CatalogApi;
#14 583.8             ~~~~~~~~~~
#14 583.8     'catalogApi' is declared here.
#14 583.8
#14 583.8
#14 583.8 Found 1 error in packages/backend/src/plugins/kubernetes.ts:9
#14 583.8
#14 584.1 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
#14 584.1 error Command failed with exit code 2.
`

**Comment by diegoluisi** [comment]
Hi @bainss 
I fixed the docker-compose.. please follow the readme.
